// Services catalog

// Fotos reais da clínica — substituir null pela path quando a cliente enviar
const IMG = {
  fisioterapia: null,
  acupuntura: null,
  mesoterapia: null,
  'fisioterapia-atm': null,
  'fisioterapia-pediatrica': null,
  'fisioterapia-vestibular': null,
  psicologia: null,
  nutricao: null,
  'terapia-bowen': null,
  'drenagem-linfatica': null,
  'massagem-relaxamento': null,
  'massagem-criancas': null,
  'massagem-assinatura-rg': null,
  'massagem-profunda': null,
  'massagem-pre-pos-natal': null,
  'massagem-sacro-craniana': null,
  'massagem-terapeutica': null,
  reflexologia: null,
  shiatsu: null,
  'massagem-indiana': null,
  'head-spa': null,
  facial: null,
  'pacotes-tratamento': null,
  'depilacao-laser': null,
  'pilates-clinico': '/assets/pilates.jpg',
  // Genéricos — fotos reais da clínica
  clinicInterior: '/assets/equipa-recepcao.png',
  clinicDetail: '/assets/rita-retrato.png',
  clinicRoom: '/assets/sala-tratamento.png',
  teamWork: '/assets/equipa-4.png',
  comunidade: '/assets/comunidade.png',
  ritaRetrato: '/assets/rita-retrato.png',
};

const SERVICES = {
  fisioterapia: {
    label: 'Fisioterapia',
    intro: 'Avaliação e tratamento individual de dor, lesão e disfunção — para crianças e adultos.',
    items: [
      { slug: 'fisioterapia-geral', name: 'Fisioterapia Geral', img: IMG.fisioterapia, blurb: 'Quando a dor ou a lesão limitam o dia-a-dia, ajudamos a recuperar — com avaliação rigorosa e um plano feito a pensar em si.', price: '50€ / Pack 5: 225€ / Pack 10: 450€' },
      { slug: 'fisioterapia-pediatrica', name: 'Fisioterapia Pediátrica', img: IMG['fisioterapia-pediatrica'], blurb: 'Fisioterapia adaptada às diferentes fases do crescimento — para bebés, crianças e adolescentes, num ambiente seguro e adequado a cada idade.', price: '50€ / Pack 5: 225€ / Pack 10: 450€' },
      { slug: 'fisioterapia-atm', name: 'Fisioterapia ATM', img: IMG['fisioterapia-atm'], blurb: 'Dor, bloqueio ou cliques na mandíbula? Tratamos a articulação temporomandibular com técnica manual especializada.', price: '60€' },
      { slug: 'mesoterapia', name: 'Mesoterapia', img: IMG.mesoterapia, blurb: 'Microinjeções com substâncias ativas para chegar à zona exata da dor, contratura ou preocupação estética — com rigor clínico.', price: '55€ / 50€' },
      { slug: 'fisioterapia-vestibular', name: 'Fisioterapia Vestibular', img: IMG['fisioterapia-vestibular'], blurb: 'Tonturas, vertigens e desequilíbrios têm tratamento — com manobras específicas e exercícios que recuperam a sua estabilidade.', price: '45€' },
    ],
  },
  saude: {
    label: 'Cuidados de Saúde',
    intro: 'Cuidados clínicos especializados para a sua saúde e bem-estar — sempre com tempo e atenção a cada pessoa.',
    items: [
      { slug: 'nutricao', name: 'Nutrição', img: IMG.nutricao, blurb: 'Um plano alimentar pensado para a sua vida real — sem dietas restritivas, com objetivos claros e acompanhamento próximo.', price: '45€ / 40€' },
      { slug: 'terapia-bowen', name: 'Terapia de Bowen', img: IMG['terapia-bowen'], blurb: 'Técnica neuromuscular suave com resultados frequentemente profundos — segura para crianças e adultos.', price: '20€ / 30€ / 60€' },
      { slug: 'psicologia', name: 'Psicologia', img: IMG.psicologia, blurb: 'Um espaço seguro e confidencial para falar do que mais preocupa — para crianças, adolescentes e adultos.', price: '45€' },
    ],
  },
  massagens: {
    label: 'Massagens',
    intro: 'Terapias manuais para libertar tensão, recuperar e devolver equilíbrio — com a técnica certa para cada momento.',
    items: [
      { slug: 'massagem-relaxamento', name: 'Massagem de Relaxamento', img: IMG['massagem-relaxamento'], blurb: 'Um espaço para parar — massagem de corpo inteiro que liberta tensão acumulada e devolve equilíbrio.', price: '40€ / 65€' },
      { slug: 'massagem-criancas', name: 'Massagem para Crianças', img: IMG['massagem-criancas'], blurb: 'Massagem suave e adaptada aos mais novos — para promover sono, calma e bem-estar.', price: '30€' },
      { slug: 'massagem-assinatura-rg', name: 'Massagem Assinatura RG', img: IMG['massagem-assinatura-rg'], blurb: 'A massagem de excelência da clínica — 80 minutos para combinar relaxamento profundo e trabalho muscular.', price: '75€' },
      { slug: 'massagem-profunda', name: 'Massagem Profunda / Desportiva', img: IMG['massagem-profunda'], blurb: 'Deep tissue e sport massage — trabalho muscular profundo para quem exige mais do corpo, no treino ou no dia-a-dia.', price: '45€ / 75€' },
      { slug: 'massagem-pre-pos-natal', name: 'Massagem Pré/Pós Natal', img: IMG['massagem-pre-pos-natal'], blurb: 'Adaptada às mudanças do corpo durante a gravidez e à recuperação no pós-parto — com conforto e posicionamento seguro.', price: '45€' },
      { slug: 'massagem-sacro-craniana', name: 'Massagem Sacro-Craniana', img: IMG['massagem-sacro-craniana'], blurb: 'Técnica de toque suave sobre o sistema sacro-craniano — alivia tensão, cefaleias e stress sem esforço.', price: '40€' },
      { slug: 'drenagem-linfatica', name: 'Drenagem Linfática Manual', img: IMG['drenagem-linfatica'], blurb: 'Método Vodder — a técnica de referência para reduzir inchaço, ativar a circulação e devolver leveza.', price: '45€ / 50€' },
      { slug: 'massagem-terapeutica', name: 'Drenagem Pós-Operatório / Terapêutica', img: IMG['massagem-terapeutica'], blurb: 'Recuperação pós-cirurgia e alívio de tensão muscular crónica — com técnica adaptada à sua condição.', price: '60€ / 80€' },
    ],
  },
  holisticas: {
    label: 'Holísticas',
    intro: 'Terapias holísticas para reequilibrar corpo e mente — com técnicas com séculos de prática e resultados sentidos.',
    items: [
      { slug: 'reflexologia', name: 'Reflexologia', img: IMG.reflexologia, blurb: 'Estimulação precisa de pontos reflexos nos pés para reequilibrar os sistemas do organismo.', price: '45€' },
      { slug: 'shiatsu', name: 'Shiatsu', img: IMG.shiatsu, blurb: 'Técnica japonesa de pressão sobre os meridianos energéticos — para devolver equilíbrio e vitalidade.', price: '45€' },
      { slug: 'massagem-indiana', name: 'Massagem Indiana', img: IMG['massagem-indiana'], blurb: 'Indian Head Massage — relaxamento profundo da cabeça, pescoço e ombros, com raízes ayurvédicas.', price: '35€' },
      { slug: 'head-spa', name: 'Head Spa', img: IMG['head-spa'], blurb: 'Tratamento profundo do couro cabeludo — limpeza, nutrição e um relaxamento que se sente em todo o corpo.', price: '80€' },
      { slug: 'acupuntura', name: 'Acupuntura', img: IMG.acupuntura, blurb: 'Medicina Tradicional Chinesa para gerir dor, stress, ansiedade, insónia e bem-estar geral — com evidência crescente.', price: '45€' },
    ],
  },
  estetica: {
    label: 'Estética & Tratamentos',
    intro: 'Cuidados estéticos e tratamentos corporais com tecnologia avançada — sempre com avaliação prévia e protocolo personalizado.',
    items: [
      { slug: 'facial', name: 'Faciais', img: IMG.facial, blurb: 'Limpeza de pele, extração e facial personalizado — para uma pele saudável e equilibrada.', price: '10€ – 55€' },
      { slug: 'pacotes-tratamento', name: 'Pacotes de Tratamento', img: IMG['pacotes-tratamento'], blurb: 'Cavitação, radiofrequência, lipolaser, eletroestimulação e pressoterapia — tecnologia ao serviço do seu corpo.', price: '25€ – 450€' },
      { slug: 'depilacao-laser', name: 'Depilação a Laser', img: IMG['depilacao-laser'], blurb: 'Depilação definitiva com tecnologia de última geração — para mulher e homem, todas as zonas.', price: 'Desde 20€/zona' },
      { slug: 'pilates-clinico', name: 'Pilates Clínico', img: IMG['pilates-clinico'], blurb: 'Pilates supervisionado por fisioterapeuta — exercício adaptado a lesões, dor crónica ou reabilitação.', price: '35€ – 60€/mês' },
    ],
  },
};

const SERVICE_DETAIL = {
  'fisioterapia-geral': {
    tagline: 'Avaliação cuidada, plano à sua medida — para voltar a mover-se com confiança.',
    description: 'A fisioterapia é uma ciência da saúde focada no estudo, prevenção, diagnóstico e tratamento de distúrbios relacionados com o movimento, a biomecânica e a capacidade funcional humana. O objetivo é restaurar, desenvolver e manter a máxima autonomia, mobilidade e qualidade de vida dos pacientes.',
    prices: [
      { label: 'Sessão (50min)', value: '50€' },
      { label: 'Pack 5 sessões', value: '225€' },
      { label: 'Pack 10 sessões', value: '450€' },
    ],
    sub: [
      { t: 'Dor lombar e cervical', d: 'Avaliação postural, terapia manual e exercício progressivo para dor da coluna — aguda ou crónica.' },
      { t: 'Recuperação pós-lesão', d: 'Acompanhamos cada pessoa desde a fase aguda até ao regresso à atividade — desporto, trabalho ou rotina diária.' },
      { t: 'Fisioterapia desportiva', d: 'Tratamento da lesão e preparação do regresso seguro à prática desportiva.' },
      { t: 'Pós-operatório', d: 'Redução de edema, ganho de mobilidade e recuperação de força após cirurgia ortopédica.' },
      { t: 'Gravidez e pós-parto', d: 'Acompanhamento das mudanças do corpo durante a gravidez e recuperação do pavimento pélvico após o parto.' },
      { t: 'Dor crónica', d: 'Abordagem integrada com terapia manual, exercício e educação em dor — para uma vida com mais autonomia.' },
    ],
    tech: {
      name: 'Winback BACK3',
      eyebrow: 'Tecnologia',
      tagline: 'Tecarterapia de última geração para acelerar a recuperação.',
      description: 'Integramos nas sessões de fisioterapia a tecnologia Winback BACK3 — um equipamento de tecarterapia (diatermia capacitiva e resistiva) que combina alta frequência (300 kHz a 1 MHz) com neuromodulação Hi-TENS e Hi-EMS. Ativa o metabolismo dos tecidos em profundidade, reduz dor e inflamação, acelera a regeneração e devolve mobilidade em menos tempo. Particularmente eficaz em lesões músculo-esqueléticas agudas e crónicas, recuperação pós-lesão, pós-cirurgia e dor desportiva.',
      img: '/assets/winback-back3.jpg',
      benefits: [
        'Alívio rápido da dor e da inflamação',
        'Aceleração da regeneração de tecidos',
        'Recuperação muscular pós-esforço',
        'Tratamento de tendinopatias e contraturas',
      ],
    },
  },
  'fisioterapia-pediatrica': {
    tagline: 'Fisioterapia adaptada a cada fase do crescimento — com cuidado, segurança e tempo para cada criança.',
    description: 'A Fisioterapia Pediátrica acompanha bebés, crianças e adolescentes em diferentes fases do desenvolvimento. Avaliamos e tratamos atrasos no desenvolvimento motor, alterações posturais, lesões músculo-esqueléticas e condições neurológicas — sempre num ambiente seguro, adaptado e adequado à idade. Cada sessão é desenhada para o ritmo da criança, com envolvimento da família sempre que faz sentido.',
    prices: [
      { label: 'Sessão (50min)', value: '50€' },
      { label: 'Pack 5 sessões', value: '225€' },
      { label: 'Pack 10 sessões', value: '450€' },
    ],
    sub: [
      { t: 'Desenvolvimento motor', d: 'Avaliação e estimulação do desenvolvimento motor em bebés e crianças com atraso ou alterações.' },
      { t: 'Alterações posturais', d: 'Escoliose, cifose, pés planos e outras alterações posturais da infância e adolescência.' },
      { t: 'Lesões músculo-esqueléticas', d: 'Recuperação de lesões desportivas, traumáticas ou por sobrecarga em crianças e jovens.' },
      { t: 'Torcicolo congénito', d: 'Tratamento manual e exercícios específicos para torcicolo muscular do bebé.' },
      { t: 'Plagiocefalia', d: 'Apoio na correção de assimetrias do crânio em bebés através de posicionamento e mobilização.' },
      { t: 'Condições neurológicas', d: 'Acompanhamento de crianças com paralisia cerebral, atraso global ou outras condições neurológicas.' },
    ],
  },
  'fisioterapia-atm': {
    tagline: 'Para quando a mandíbula dói, bloqueia ou faz cliques — tratamos a ATM na sua raiz.',
    description: 'A fisioterapia para a articulação temporomandibular (ATM) trata a disfunção (DTM) através de terapias manuais e exercícios. O objetivo é aliviar dores de cabeça ou na face, eliminar estalidos, reduzir a tensão e restaurar a mobilidade, sendo muitas vezes integrada num acompanhamento médico multidisciplinar.',
    prices: [
      { label: 'Fisioterapia ATM (50min)', value: '60€' },
    ],
    sub: [
      { t: 'Dor na mandíbula', d: 'Alívio de dor articular, muscular ou ao mastigar através de terapia manual especializada.' },
      { t: 'Cliques e rangido', d: 'Avaliação e tratamento dos estalidos, cliques ou crepitações na articulação ao abrir ou fechar a boca.' },
      { t: 'Bloqueio articular', d: 'Recuperação da amplitude de movimento da mandíbula em casos de bloqueio ou limitação de abertura.' },
      { t: 'Cefaleias e tensão cervical', d: 'Abordagem integrada entre ATM, cervical e cefaleias — muitas vezes interligadas.' },
      { t: 'Bruxismo', d: 'Gestão da tensão muscular e proteção articular em casos de bruxismo diurno ou noturno.' },
      { t: 'Pós-ortodontia ou pós-cirurgia', d: 'Recuperação funcional da ATM após tratamentos dentários, ortodônticos ou cirúrgicos.' },
    ],
  },
  mesoterapia: {
    tagline: 'Ação localizada onde mais precisa — para dor, inflamação ou cuidado estético.',
    description: 'A Mesoterapia consiste na aplicação de microinjeções de substâncias ativas diretamente nas camadas superficiais da pele ou tecido subcutâneo. Permite uma ação altamente localizada — chega à zona exata da dor, contratura ou da preocupação estética, com pouca difusão sistémica. Aplicada por fisioterapeuta com formação específica, é uma técnica versátil tanto em contexto clínico (dor articular, contraturas) como estético (celulite, flacidez, rejuvenescimento).',
    prices: [
      { label: 'Sessão (50min)', value: '55€ / 50€' },
    ],
    sub: [
      { t: 'Dor e inflamação articular', d: 'Aplicação localizada de anti-inflamatórios para alívio rápido em joelhos, ombros ou coluna.' },
      { t: 'Contraturas musculares', d: 'Libertação de pontos de tensão muscular persistentes resistentes a outras técnicas.' },
      { t: 'Celulite e gordura localizada', d: 'Melhoria da circulação local e redução de acumulações de gordura em zonas específicas.' },
      { t: 'Flacidez cutânea', d: 'Estimulação da produção de colagénio para firmeza e tonicidade da pele.' },
      { t: 'Rejuvenescimento facial', d: 'Hidratação profunda e revitalização da pele do rosto com ácido hialurónico e vitaminas.' },
      { t: 'Queda de cabelo', d: 'Estimulação do couro cabeludo para fortalecimento capilar e travagem da queda.' },
    ],
  },
  'fisioterapia-vestibular': {
    tagline: 'Recuperar a estabilidade — e voltar a confiar no equilíbrio do seu corpo.',
    description: 'A Fisioterapia Vestibular é uma área especializada da fisioterapia que trata tonturas, vertigens e desequilíbrios. Através de avaliação rigorosa, manobras de reposicionamento (eficazes em VPPB) e exercícios específicos de habituação e estabilização do olhar, ajudamos o sistema vestibular a recuperar ou compensar. Os resultados são frequentemente rápidos — em muitos casos, com alívio significativo logo na primeira sessão.',
    prices: [
      { label: 'Por sessão (50min)', value: '45€' },
    ],
    sub: [
      { t: 'Vertigem Posicional (VPPB)', d: 'Manobras de reposicionamento de otólitos — resolução frequente em 1 a 3 sessões.' },
      { t: 'Tonturas crónicas', d: 'Exercícios de habituação e estabilização do olhar para reduzir tonturas persistentes.' },
      { t: 'Neurite vestibular', d: 'Reabilitação após inflamação do nervo vestibular para recuperar equilíbrio e estabilidade.' },
      { t: 'Doença de Ménière', d: 'Apoio na gestão de crises vertiginosas e melhoria do equilíbrio entre episódios.' },
      { t: 'Desequilíbrio no idoso', d: 'Treino de equilíbrio e prevenção de quedas em populações com risco aumentado.' },
      { t: 'Tonturas pós-traumáticas', d: 'Recuperação após traumatismo craniano ou cervical com sintomas vestibulares.' },
    ],
  },
  acupuntura: {
    tagline: 'Uma medicina com séculos de prática — e evidência crescente para o seu bem-estar.',
    description: 'A acupuntura é uma técnica terapêutica milenar, originária da Medicina Tradicional Chinesa, que consiste na inserção de agulhas finas em pontos específicos do corpo. O seu objetivo é estimular respostas naturais do organismo, promovendo o equilíbrio físico e emocional e o alívio de sintomas.',
    prices: [
      { label: 'Por sessão (50min)', value: '45€' },
    ],
    sub: [
      { t: 'Dor crónica', d: 'Lombalgias, cervicalgias, cefaleias e dores articulares com resposta comprovada à acupuntura.' },
      { t: 'Stress e ansiedade', d: 'Regulação do sistema nervoso autónomo para reduzir tensão, irritabilidade e fadiga mental.' },
      { t: 'Insónia', d: 'Tratamento das causas subjacentes ao sono perturbado através do equilíbrio energético.' },
      { t: 'Saúde digestiva', d: 'Colon irritável, refluxo e outros desequilíbrios do sistema digestivo.' },
      { t: 'Fertilidade e ciclo menstrual', d: 'Regulação hormonal e apoio em processos de fertilidade ou desconfortos menstruais.' },
      { t: 'Bem-estar geral', d: 'Equilíbrio energético e bem-estar global como prática preventiva e de saúde.' },
    ],
  },
  nutricao: {
    tagline: 'Alimentação real para a vida real — sem dietas restritivas nem soluções genéricas.',
    description: 'A nutrição é a ciência que estuda a relação entre os alimentos ingeridos, a sua composição e o impacto direto no funcionamento do corpo, na saúde e na prevenção de doenças. O processo biológico envolve a ingestão, absorção e utilização de nutrientes para o crescimento, energia e manutenção da vida.',
    prices: [
      { label: '1ª consulta (até 50min)', value: '45€' },
      { label: 'Seguintes (30min)', value: '40€' },
    ],
    sub: [
      { t: 'Perda de peso sustentável', d: 'Plano alimentar real e adaptado ao seu estilo de vida — para perder e manter.' },
      { t: 'Nutrição desportiva', d: 'Otimização da alimentação para performance, recuperação e composição corporal.' },
      { t: 'Saúde digestiva', d: 'Apoio nutricional em colon irritável, intolerâncias, refluxo e outros desequilíbrios.' },
      { t: 'Diabetes e colesterol', d: 'Gestão nutricional de patologias metabólicas com acompanhamento regular.' },
      { t: 'Gravidez e amamentação', d: 'Alimentação adaptada a cada fase, para a saúde da mãe e do bebé.' },
      { t: 'Alimentação vegetariana e vegana', d: 'Garantia de equilíbrio nutricional em dietas plant-based sem défices.' },
    ],
  },
  'terapia-bowen': {
    tagline: 'Suave no toque, eficaz no resultado — para todas as idades.',
    description: 'A terapia de Bowen é uma técnica manual holística e não invasiva que utiliza toques suaves e precisos sobre músculos, tendões e ligamentos. O seu principal objetivo é estimular os mecanismos naturais de autocura do corpo e restaurar o equilíbrio do sistema nervoso, promovendo o alívio da dor e o relaxamento.',
    prices: [
      { label: 'Crianças até 5 anos (60min)', value: '20€' },
      { label: 'Crianças 5-12 anos (60min)', value: '30€' },
      { label: 'Adultos +12 anos (60min)', value: '60€' },
    ],
    sub: [
      { t: 'Dor lombar e cervical', d: 'Libertação de tensões profundas na coluna com uma técnica completamente suave.' },
      { t: 'Fibromialgia', d: 'Abordagem eficaz para a gestão da dor difusa e da fadiga crónica associadas à fibromialgia.' },
      { t: 'Tensão e stress crónico', d: 'Ativação do sistema nervoso parassimpático para um estado de calma e regeneração.' },
      { t: 'Lesões desportivas', d: 'Recuperação de lesões musculares e tendinosas com menor tempo de paragem.' },
      { t: 'Enxaqueca e cefaleia tensional', d: 'Redução da frequência e intensidade das crises através do equilíbrio muscular e fascial.' },
      { t: 'Crianças', d: 'Técnica completamente segura e suave, indicada a partir dos 5 anos de idade.' },
    ],
  },
  psicologia: {
    tagline: 'Um espaço seguro para falar do que o(a) preocupa — para criança, adolescente e adulto.',
    description: 'A psicologia é a ciência que estuda o comportamento humano, os processos mentais e a forma como as emoções, os pensamentos e o ambiente interagem. O seu principal objetivo é compreender, explicar e promover a saúde mental e o bem-estar, ajudando as pessoas a lidar com desafios e a melhorar a sua qualidade de vida.',
    prices: [
      { label: 'Consulta (60min)', value: '45€' },
    ],
    sub: [
      { t: 'Ansiedade e stress', d: 'Ferramentas práticas para gerir preocupação excessiva, tensão e sintomas físicos associados.' },
      { t: 'Depressão e humor', d: 'Acompanhamento de estados depressivos, tristeza persistente e perda de motivação.' },
      { t: 'Psicologia infantil', d: 'Apoio a crianças com dificuldades de comportamento, atenção, aprendizagem ou adaptação.' },
      { t: 'Adolescência', d: 'Suporte em processos de identidade, pressão social, autoestima e gestão emocional.' },
      { t: 'Luto e perda', d: 'Acompanhamento em processos de perda — de pessoas, relações, saúde ou projetos de vida.' },
      { t: 'Relações e comunicação', d: 'Trabalho sobre padrões relacionais, assertividade e dinâmicas interpessoais.' },
    ],
  },
  'massagem-relaxamento': {
    tagline: 'Tempo para parar — com técnica e cuidado.',
    description: 'A massagem de relaxamento é uma terapia manual que utiliza movimentos suaves, rítmicos e contínuos em todo o corpo, com o auxílio de óleos ou cremes. O seu objetivo principal é aliviar tensões musculares, reduzir o stress e promover um estado de bem-estar físico e mental profundo.',
    prices: [
      { label: '50 minutos', value: '40€' },
      { label: '80 minutos', value: '65€' },
    ],
    sub: [
      { t: 'Tensão muscular generalizada', d: 'Libertação de contraturas e pontos de tensão acumulados no dia-a-dia.' },
      { t: 'Stress e sobrecarga mental', d: 'Ativação do sistema nervoso parassimpático para uma resposta de calma profunda.' },
      { t: 'Distúrbios do sono', d: 'A massagem regular melhora a qualidade do sono e facilita o adormecer.' },
      { t: 'Dores de cabeça tensionais', d: 'Trabalho sobre pescoço, ombros e couro cabeludo para aliviar cefaleias de tensão.' },
      { t: 'Circulação e drenagem', d: 'Melhoria do fluxo sanguíneo e linfático para um corpo mais leve e vital.' },
      { t: 'Bem-estar preventivo', d: 'Uma sessão regular é um investimento na saúde — não um luxo.' },
    ],
  },
  'massagem-criancas': {
    tagline: 'Toque suave e seguro — para o bem-estar dos mais novos.',
    description: 'A massagem de relaxamento para crianças é uma prática suave que alia técnicas terapêuticas adaptadas à idade infantil. Ajuda a reduzir o stress e a ansiedade, melhora a qualidade do sono, diminui dores de crescimento e promove um forte desenvolvimento emocional e segurança.',
    prices: [
      { label: 'Por sessão (40min)', value: '30€' },
    ],
    sub: [
      { t: 'Relaxamento e sono', d: 'Técnica suave para promover um sono mais tranquilo e profundo nas crianças.' },
      { t: 'Ansiedade infantil', d: 'Redução do stress e ansiedade com toque terapêutico e ambiente seguro.' },
      { t: 'Cólicas e digestão', d: 'Massagem abdominal suave para alívio de cólicas e desconforto digestivo.' },
      { t: 'Desenvolvimento motor', d: 'Estimulação sensorial e motora para o desenvolvimento saudável da criança.' },
      { t: 'Tensão muscular', d: 'Libertação de tensão acumulada em crianças ativas ou com postura inadequada.' },
      { t: 'Bem-estar geral', d: 'Sessão de bem-estar para crianças que simplesmente precisam de um momento de cuidado.' },
    ],
  },
  'massagem-assinatura-rg': {
    tagline: 'Oitenta minutos pensados ao detalhe — a experiência de assinatura da casa.',
    description: 'A Massagem Assinatura RG é a experiência mais completa que a clínica Rita Guerreiro oferece. Uma sessão de 80 minutos, cuidadosamente desenhada para combinar relaxamento profundo, trabalho muscular específico e bem-estar global. Cada momento é personalizado de acordo consigo — do início ao fim.',
    prices: [
      { label: 'Sessão completa (80min)', value: '75€' },
    ],
    sub: [
      { t: 'Relaxamento total', d: 'Combinação de técnicas suaves para induzir um estado de calma profunda.' },
      { t: 'Trabalho muscular', d: 'Libertação de tensões acumuladas com técnicas adaptadas a cada zona do corpo.' },
      { t: 'Bem-estar global', d: 'Abordagem holística que cuida do corpo e da mente em simultâneo.' },
      { t: 'Experiência personalizada', d: 'Cada sessão é adaptada às preferências e necessidades do cliente.' },
      { t: 'Momento único', d: '80 minutos de dedicação exclusiva ao seu bem-estar.' },
      { t: 'Ideal para oferta', d: 'A escolha perfeita para uma prenda especial ou um momento de autocuidado.' },
    ],
  },
  'massagem-profunda': {
    tagline: 'Trabalho muscular profundo — para quem exige mais do corpo, no treino ou no dia-a-dia.',
    description: 'A massagem deep tissue (ou massagem de tecido profundo) é uma técnica terapêutica focada nas camadas mais profundas dos músculos e do tecido conjuntivo. Utiliza movimentos lentos e pressão firme para aliviar dores crónicas, nós musculares (aderências) e recuperar a mobilidade.',
    prices: [
      { label: '50 minutos', value: '45€' },
      { label: '80 minutos', value: '75€' },
    ],
    sub: [
      { t: 'Contraturas e espasmos musculares', d: 'Libertação de nós musculares e zonas de tensão profunda resistentes ao relaxamento espontâneo.' },
      { t: 'Recuperação pós-treino', d: 'Aceleração da regeneração muscular, redução de DOMS e eliminação de resíduos metabólicos após esforço intenso.' },
      { t: 'Preparação pré-competição', d: 'Ativação muscular e mobilização dos tecidos para otimizar o rendimento desportivo antes da prova ou treino.' },
      { t: 'Síndrome do piriforme e ciática', d: 'Trabalho específico sobre a musculatura glútea profunda para alívio da dor ciática e libertação do nervo.' },
      { t: 'Tensão cervical e ombros', d: 'Abordagem profunda na zona mais afetada por stress, trabalho sedentário e postura anterior.' },
      { t: 'Tendinites e sobrecargas', d: 'Tratamento de tendinites crónicas e lesões por esforço repetitivo em atletas e não-atletas.' },
    ],
  },
  'massagem-pre-pos-natal': {
    tagline: 'Acompanhamento e conforto na gravidez e no pós-parto — adaptado a cada fase.',
    description: 'A massagem pré e pós-natal é um tratamento terapêutico focado no alívio de dores musculares, inchaço e stress, adaptado às transformações do corpo da mulher. Na pré-natal (gravidez), melhora a circulação e reduz o desconforto; na pós-natal, ajuda a recuperar o tónus muscular e o equilíbrio emocional.',
    prices: [
      { label: 'Por sessão (50min)', value: '45€' },
    ],
    sub: [
      { t: 'Dor lombar na gravidez', d: 'Alívio das dores lombares e pélvicas típicas da gestação, com posicionamento seguro.' },
      { t: 'Inchaço e retenção', d: 'Melhoria da circulação e redução do inchaço nas pernas e tornozelos durante a gravidez.' },
      { t: 'Tensão muscular', d: 'Libertação de tensões no pescoço, ombros e costas acumuladas com o peso da barriga.' },
      { t: 'Recuperação pós-parto', d: 'Apoio na recuperação física após o parto — dor muscular, tensão e bem-estar geral.' },
      { t: 'Equilíbrio emocional', d: 'Momento de cuidado e relaxamento num período de tantas mudanças emocionais.' },
      { t: 'Sono e descanso', d: 'Técnicas para melhorar a qualidade do sono — tão difícil durante a gravidez e após o parto.' },
    ],
  },
  'massagem-sacro-craniana': {
    tagline: 'Um toque quase imperceptível com efeitos profundos no sistema nervoso.',
    description: 'A terapia craniana (ou terapia craniossacral/sacro-craniana) é uma técnica manual suave e não invasiva que atua no sistema craniossacral, o qual inclui os ossos do crânio, a coluna, o sacro e o líquido cefalorraquidiano. Através de toques muito leves (cerca de 5 gramas), o terapeuta liberta bloqueios e tensões, promovendo o auto-equilíbrio do corpo e o relaxamento profundo do sistema nervoso central.',
    prices: [
      { label: 'Por sessão (50min)', value: '40€' },
    ],
    sub: [
      { t: 'Cefaleias e enxaquecas', d: 'Libertação de tensões craniossacrais que contribuem para dores de cabeça recorrentes.' },
      { t: 'Stress e ansiedade', d: 'Ativação profunda do sistema nervoso parassimpático para equilíbrio emocional.' },
      { t: 'Disfunções da ATM', d: 'Alívio de dores e tensões na articulação temporomandibular e face.' },
      { t: 'Dor cervical', d: 'Libertação de tensões na região cervical e base do crânio.' },
      { t: 'Insónia', d: 'Promoção de um estado de descanso profundo que melhora a qualidade do sono.' },
      { t: 'Bebés e crianças', d: 'Técnica completamente segura para os mais novos, indicada para cólicas e tensões do parto.' },
    ],
  },
  'drenagem-linfatica': {
    tagline: 'Reduz o inchaço, ativa a circulação, devolve leveza — com o Método Vodder.',
    description: 'A drenagem linfática manual (DLM) é uma técnica de massagem terapêutica especializada que utiliza movimentos rítmicos, suaves e lentos. O seu principal objetivo é estimular o sistema linfático, acelerando a eliminação de líquidos, toxinas e resíduos metabólicos através da urina.',
    prices: [
      { label: 'Manual (50min)', value: '50€ / 45€ (Pack 10)' },
      { label: 'Pós-Operatório 50min', value: '60€' },
      { label: 'Pós-Operatório 80min', value: '80€' },
    ],
    sub: [
      { t: 'Retenção de líquidos', d: 'Redução do inchaço nas pernas, tornozelos e barriga causado por retenção hídrica.' },
      { t: 'Pós-cirurgia e cicatrização', d: 'Aceleração da recuperação, redução de edema e melhoria da qualidade das cicatrizes.' },
      { t: 'Linfedema', d: 'Gestão do linfedema primário ou secundário com técnica especializada Método Vodder.' },
      { t: 'Celulite', d: 'Melhoria da aparência da pele e da microcirculação local em zonas afetadas por celulite.' },
      { t: 'Sistema imunitário', d: 'Estimulação das defesas naturais do organismo e eliminação de resíduos metabólicos.' },
      { t: 'Bem-estar e leveza', d: 'Sensação de corpo mais leve, pernas cansadas aliviadas e mente mais relaxada.' },
    ],
  },
  'massagem-terapeutica': {
    tagline: 'Para recuperar depois da cirurgia — e para libertar a tensão que não passa.',
    description: 'A drenagem linfática pós-operatória é uma massagem suave e terapêutica essencial para a recuperação de cirurgias plásticas ou clínicas. Ela reduz o inchaço (edema), diminui hematomas, alivia dores e previne complicações como fibroses e seromas, acelerando a cicatrização. A massagem terapêutica é uma técnica manual focada no tratamento de disfunções musculares, articulares e dores localizadas. Utiliza movimentos específicos e com mais pressão para aliviar tensões, melhorar a mobilidade e promover a recuperação física. Diferencia-se da massagem de relaxamento por ter um objetivo clínico e curativo, e não apenas de bem-estar geral.',
    prices: [
      { label: 'Terapêutica 30-50min', value: '30€ – 45€ / 40€' },
      { label: 'Drenagem Pós-Op 50min', value: '60€' },
      { label: 'Drenagem Pós-Op 80min', value: '80€' },
    ],
    sub: [
      { t: 'Recuperação pós-cirurgia', d: 'Redução de edema e melhoria da qualidade das cicatrizes após intervenção cirúrgica.' },
      { t: 'Contraturas e espasmos', d: 'Libertação de nós musculares e zonas de tensão profunda resistentes ao relaxamento.' },
      { t: 'Dor pós-exercício', d: 'Aceleração da recuperação muscular e redução da inflamação após treino intenso.' },
      { t: 'Tensão cervical e ombros', d: 'Abordagem profunda na zona mais afetada por trabalho sedentário e stress.' },
      { t: 'Tendinites e sobrecargas', d: 'Tratamento de tendinites crónicas e sobrecargas por esforço repetitivo.' },
      { t: 'Recuperação desportiva', d: 'Protocolo específico para atletas — antes ou depois da competição ou treino.' },
    ],
  },
  reflexologia: {
    tagline: 'O corpo todo nos pés — uma terapia não invasiva com efeitos profundos.',
    description: 'A reflexologia é uma técnica terapêutica não invasiva que consiste na aplicação de pressão em áreas específicas dos pés, mãos ou orelhas. Baseia-se no princípio de que estas zonas correspondem a reflexos diretos de diferentes órgãos, glândulas e partes do corpo.',
    prices: [
      { label: 'Por sessão (50min)', value: '45€' },
    ],
    sub: [
      { t: 'Stress e ansiedade', d: 'Estimulação do sistema nervoso parassimpático para redução da tensão e ansiedade.' },
      { t: 'Insónia', d: 'Regulação do sono através do equilíbrio dos sistemas do organismo.' },
      { t: 'Dores de cabeça', d: 'Trabalho sobre os pontos reflexos correspondentes à cabeça e sistema nervoso.' },
      { t: 'Saúde digestiva', d: 'Estimulação dos reflexos do sistema digestivo para melhoria da função intestinal.' },
      { t: 'Circulação', d: 'Melhoria da circulação sanguínea e linfática através da estimulação reflexa.' },
      { t: 'Bem-estar geral', d: 'Sessão de equilíbrio e relaxamento profundo para corpo e mente.' },
    ],
  },
  shiatsu: {
    tagline: 'Pressão precisa sobre os meridianos — para devolver equilíbrio e vitalidade.',
    description: 'O shiatsu é uma terapia corporal e massagem terapêutica de origem japonesa cujo nome significa literalmente "pressão com os dedos" (shi = dedos + atsu = pressão). A técnica foca no reequilíbrio físico e energético.',
    prices: [
      { label: 'Por sessão (50min)', value: '45€' },
    ],
    sub: [
      { t: 'Dor muscular e articular', d: 'Alívio de dores e tensões musculares através da pressão nos meridianos energéticos.' },
      { t: 'Fadiga e falta de energia', d: 'Estimulação do fluxo de energia vital para recuperação da vitalidade.' },
      { t: 'Stress e ansiedade', d: 'Equilíbrio do sistema nervoso para redução do stress e promoção do bem-estar.' },
      { t: 'Dores de cabeça', d: 'Libertação de tensões no pescoço, ombros e cabeça que provocam cefaleias.' },
      { t: 'Problemas digestivos', d: 'Estimulação dos meridianos relacionados com o sistema digestivo.' },
      { t: 'Equilíbrio emocional', d: 'Harmonia entre o físico e o emocional através da regulação energética.' },
    ],
  },
  'massagem-indiana': {
    tagline: 'Indian Head Massage — relaxamento profundo da cabeça, pescoço e ombros, sem ter de se despir.',
    description: 'A massagem indiana envolve movimentos ritmados, lentos e profundos, aplicados em pontos específicos do corpo para liberar tensões, melhorar a circulação sanguínea e eliminar toxinas.',
    prices: [
      { label: 'Por sessão (40min)', value: '35€' },
    ],
    sub: [
      { t: 'Cefaleias e tensão craniana', d: 'Libertação de tensão acumulada no couro cabeludo, pescoço e ombros.' },
      { t: 'Stress e sobrecarga mental', d: 'Indução de estado de relaxamento profundo com técnicas de raiz ayurvédica.' },
      { t: 'Circulação no couro cabeludo', d: 'Melhoria da circulação local, benéfica para a saúde e crescimento do cabelo.' },
      { t: 'Tensão cervical', d: 'Trabalho específico sobre a região cervical, pescoço e ombros.' },
      { t: 'Fadiga visual', d: 'Técnicas suaves sobre a face e área orbital para alívio da fadiga ocular.' },
      { t: 'Equilíbrio energético', d: 'Trabalho sobre os chakras superiores para harmonia física e emocional.' },
    ],
  },
  'head-spa': {
    tagline: 'Cuidar do couro cabeludo é cuidar do cabelo — e relaxar como há muito não relaxava.',
    description: 'O head spa japonês é uma terapia capilar e holística de relaxamento profundo. Originária do Japão, foca na saúde do couro cabeludo através de limpeza, esfoliação e massagens estimulantes na cabeça, pescoço e ombros. O tratamento alivia o stresse, melhora a circulação sanguínea e promove o bem-estar geral.',
    prices: [
      { label: 'Sessão completa (90min)', value: '80€' },
    ],
    sub: [
      { t: 'Limpeza profunda', d: 'Remoção do excesso de sebo, células mortas e impurezas do couro cabeludo.' },
      { t: 'Nutrição e hidratação', d: 'Aplicação de ativos nutritivos para fortalecer os folículos e revitalizar o cabelo.' },
      { t: 'Queda de cabelo', d: 'Estimulação da circulação no couro cabeludo para fortalecer os folículos capilares.' },
      { t: 'Couro cabeludo sensível', d: 'Tratamento suave e equilibrante para couro cabeludo irritado ou com caspa.' },
      { t: 'Massagem relaxante', d: 'Massagem profunda do couro cabeludo para libertação de tensão e promoção do bem-estar.' },
      { t: 'Brilho e vitalidade', d: 'Resultados visíveis no aspeto do cabelo — mais brilhante, leve e saudável.' },
    ],
  },
  facial: {
    tagline: 'Cuidado profissional para cada tipo de pele — para resultados visíveis e duradouros.',
    description: 'A limpeza de pele é um procedimento estético fundamental para remover impurezas, células mortas, excesso de oleosidade. O processo desobstrui os poros, melhora a oxigenação e potencializa a absorção de produtos de cuidado diário. A limpeza de pele com extração é um procedimento estético profissional essencial para desobstruir os poros, eliminar pontos negros (comedões), brancos (miliuns) e células mortas. O processo devolve o viço e a saúde à pele, sendo realizado através de etapas rigorosas de higiene, emoliência e hidratação.',
    prices: [
      { label: 'Limpeza de Pele', value: '50€' },
      { label: 'Extração', value: '10€' },
      { label: 'Facial Personalizado', value: '55€' },
    ],
    sub: [
      { t: 'Limpeza de pele', d: 'Tratamento completo de limpeza para remover impurezas, sebo e células mortas.' },
      { t: 'Extração', d: 'Remoção profissional de comedões e impurezas de forma segura e eficaz.' },
      { t: 'Facial personalizado', d: 'Tratamento adaptado ao tipo de pele — hidratação, anti-age, luminosidade ou controlo de oleosidade.' },
      { t: 'Pele acneica', d: 'Protocolo específico para peles com tendência acneica e excesso de oleosidade.' },
      { t: 'Anti-age', d: 'Tratamentos com ativos que estimulam o colagénio e reduzem os sinais do envelhecimento.' },
      { t: 'Hidratação profunda', d: 'Reposição intensiva de hidratação para peles secas, desidratadas ou sensíveis.' },
    ],
  },
  'pacotes-tratamento': {
    tagline: 'Tecnologia avançada com avaliação prévia — para resultados reais, não promessas.',
    description: 'A cavitação e a radiofrequência são tratamentos estéticos não invasivos complementares. A cavitação usa ultrassons para eliminar a gordura localizada destruindo as células adiposas. A radiofrequência usa ondas eletromagnéticas para aquecer a pele, estimulando o colágeno, reduzindo a flacidez e melhorando o aspeto da celulite. A pressoterapia é um tratamento de drenagem linfática mecânica que utiliza pressão de ar controlada para estimular a circulação sanguínea e o sistema linfático. É realizada através de acessórios com câmaras de ar (como botas ou mangas) que insuflam e desinsuflam sequencialmente, ajudando a eliminar líquidos e toxinas.',
    prices: [
      { label: 'Cav./Radiofrequência/Lipolaser/Eletroestim. (50min)', value: '50€' },
      { label: 'Pacote 10 sessões', value: '450€' },
      { label: 'Pressoterapia 30-50min', value: '25€ / 35€' },
    ],
    sub: [
      { t: 'Cavitação', d: 'Ultrassons focados para destruição de células adiposas em zonas localizadas.' },
      { t: 'Radiofrequência', d: 'Estimulação do colagénio e elastina para firmeza da pele e redução da flacidez.' },
      { t: 'Lipolaser', d: 'Laser de baixa intensidade para mobilização de gordura localizada e modelação corporal.' },
      { t: 'Electroestimulação', d: 'Contração muscular passiva para tonificação e recuperação de zonas específicas.' },
      { t: 'Pressoterapia', d: 'Drenagem linfática mecânica por pressão sequencial — inchaço, circulação e recuperação.' },
      { t: 'Pacote 10 sessões', d: 'Aproveite o pacote de 10 sessões — ideal para resultados progressivos e duradouros.' },
    ],
  },
  'depilacao-laser': {
    tagline: 'Acaba com a depilação semanal — laser definitivo, para mulher e homem.',
    description: 'A depilação a laser é um procedimento estético que utiliza feixes de luz concentrada para destruir a raiz do pelo (folículo piloso), retardando e reduzindo o seu crescimento de forma prolongada.',
    prices: [
      { label: 'Mulher — 1 zona', value: '20€' },
      { label: 'Mulher — Combi 3 zonas', value: '50€' },
      { label: 'Mulher — Zona extra', value: '10€' },
      { label: 'Homem — 1 zona', value: '20€' },
      { label: 'Homem — Combi 3 zonas', value: '60€' },
      { label: 'Homem — Zona extra', value: '10€' },
    ],
    sub: [
      { t: 'Virilha e linha do biquíni', d: 'Tratamento completo ou parcial, com opções adaptadas às suas preferências.' },
      { t: 'Pernas e coxas', d: 'Depilação de zonas extensas com eficácia e conforto máximos.' },
      { t: 'Axilas', d: 'Uma das zonas com resultado mais rápido — frequentemente eficaz em poucas sessões.' },
      { t: 'Rosto e pescoço', d: 'Lábio superior, queixo, bochechas e zona do pescoço, com extrema precisão.' },
      { t: 'Costas e peito', d: 'Tratamento de zonas extensas no corpo masculino, com equipamento adequado.' },
      { t: 'Braços e antebraços', d: 'Resultados graduais e permanentes nesta zona com elevada densidade de pelo.' },
    ],
  },
  'pilates-clinico': {
    tagline: 'Pilates com supervisão de fisioterapeuta — exercício adaptado, sempre seguro.',
    description: 'O pilates clínico é uma modalidade de exercício terapêutico, focado na prevenção e reabilitação de lesões músculo-esqueléticas. Distingue-se do pilates tradicional por ser ministrado exclusivamente por fisioterapeutas, que adaptam os exercícios à condição clínica e às necessidades específicas de cada pessoa.',
    prices: [
      { label: 'Mensalidade', value: '35€ / 60€' },
      { label: 'Seguro Anual', value: '10€' },
      { label: 'Personalizado (50min)', value: '45€' },
    ],
    sub: [
      { t: 'Dor lombar e hérnias', d: 'Fortalecimento do core profundo para estabilizar a coluna e reduzir a dor crónica.' },
      { t: 'Pós-operatório', d: 'Reintegração progressiva do movimento após cirurgia ortopédica, abdominal ou outra.' },
      { t: 'Gravidez e pós-parto', d: 'Exercícios adaptados para cada fase — preparação para o parto e recuperação após.' },
      { t: 'Osteoporose', d: 'Treino de força e equilíbrio com baixo impacto articular, para prevenir quedas e fraturas.' },
      { t: 'Escoliose e desvios posturais', d: 'Correção progressiva dos padrões posturais alterados com exercício supervisionado.' },
      { t: 'Performance e prevenção', d: 'Para quem quer melhorar a consciência corporal e prevenir lesões na prática desportiva.' },
    ],
  },
};

Object.assign(window, { SERVICES, SERVICE_DETAIL, IMG });
