// Design tokens — Rita Guerreiro · clean, white-first

const RG = {
  // Teal do logo (usada com parcimónia, como acento)
  teal: '#6FB5B0',
  tealDeep: '#4A8F8A',
  tealDark: '#2F6B68',
  tealInk: '#1F4846',
  tealWash: '#F1F7F6',       // background wash muito ténue
  // Neutros limpos
  cream: '#FFFFFF',          // antes era #F6F1E9 — agora branco
  creamSoft: '#FAFAF8',      // wash quase branco
  white: '#FFFFFF',
  ink: '#141412',
  graphite: '#2B2B27',
  charcoal: '#55554E',
  muted: '#8A8A82',
  line: '#E8E6DF',
  lineSoft: '#F0EEE7',
};

const F_DISPLAY = '"Open Sans", system-ui, sans-serif';
const F_BODY = '"DM Sans", -apple-system, BlinkMacSystemFont, sans-serif';
const F_MONO = '"JetBrains Mono", ui-monospace, monospace';

Object.assign(window, { RG, F_DISPLAY, F_BODY, F_MONO });

// ── i18n ──────────────────────────────────────────────────────────────────────
const TRANSLATIONS = {
  PT: {
    nav: {
      inicio: 'Início', servicos: 'Serviços', sobre: 'Sobre', contactos: 'Contactos',
      mega_descs: {
        fisioterapia: 'Reabilitação e movimento',
        saude: 'Bem-estar integral',
        massagens: 'Relaxamento e terapia',
        holisticas: 'Equilíbrio e energia',
        estetica: 'Beleza e cuidado',
      },
    },
    nav_mobile: { inicio: 'Início', servicos: 'Serviços', sobre: 'Sobre', contactos: 'Contactos' },
    hero: {
      badge: 'Loulé · Algarve',
      badge_v2: 'Em Loulé desde 2022',
      h1: ['Recupera', 'Equilibra', 'Sente-te bem'],
      desc: 'Fisioterapia, Osteopatia, Pilates Clínico, Psicologia e muito mais — numa clínica em Loulé onde cada pessoa é tratada com atenção e cuidado real.',
      cta: 'Marcar consulta',
      cta_secondary: 'Conhecer tratamentos',
      cta_tel: 'Ligar agora',
      horario: 'Seg–Sex 9h–19h · Sábados sob marcação',
      social_proof: '+500 pacientes acompanhados · Google 5★',
      social_proof_v2: '+500 pacientes acompanhados',
      next_slot_label: 'Próxima vaga',
      next_slot_value: 'Quinta-feira · 14h30',
      next_slot_meta: 'Fisioterapia · 50 min · [REVER manualmente]',
      card_name: 'Centro de Terapias Rita Guerreiro',
      card_addr: 'Rua Padre António Vieira 58, Loulé',
    },
    trust: {
      anos: 'anos de prática',
      anos_desc: 'Experiência consolidada em fisioterapia e reabilitação no Algarve.',
      pacientes: 'Pacientes acompanhados',
      terapias: 'Terapias disponíveis',
      cred_title: 'Cédula profissional',
      cred_desc: 'Fisioterapeuta inscrita na Ordem dos Fisioterapeutas Portugueses. [REVER nº cédula]',
    },
    services_menu: {
      '01_name': 'Fisioterapia',
      '02_name': 'Pilates Clínico',
      '03_name': 'Massagens Terapêuticas',
      '04_name': 'Psicologia & Nutrição',
      '01_blurb': 'Avaliação e tratamento individual de dor, lesão e disfunção — para crianças e adultos. Sessões de 50 a 80 minutos.',
      '02_blurb': 'Movimento consciente supervisionado por fisioterapeuta — adaptado a dor lombar, gravidez, pós-operatório e prevenção de lesões.',
      '03_blurb': 'Massagens terapêuticas, deep tissue, pré/pós-natal, sacro-craniana e a exclusiva Massagem Assinatura RG (80 min).',
      '04_blurb': 'Acompanhamento psicológico e plano alimentar individualizado — porque a saúde é mais do que o corpo.',
    },
    meet: {
      eyebrow: 'Conhece a Rita',
      heading: 'A pessoa por trás do projeto',
      p1: 'A Rita Guerreiro fundou este centro em Loulé com uma convicção simples: cada pessoa merece ser ouvida antes de ser tratada. Mais de duas décadas em fisioterapia ensinaram-na que os melhores resultados vêm de planos individuais — não de protocolos genéricos.',
      p2: 'Hoje, lidera uma equipa multidisciplinar que trabalha em conjunto para que tu não tenhas de mudar de clínica conforme a necessidade. Tudo num só sítio, com continuidade e respeito pela tua história. [REVER bio]',
      card_label: 'Fundadora · Fisioterapeuta',
      card_name: 'Rita Guerreiro',
      card_credentials: 'Fisioterapeuta · Especialização em ATM, Vestibular e Pilates Clínico. [REVER credenciais]',
      facts: [
        { value: '2015', label: 'Início da prática clínica [REVER]' },
        { value: '2022', label: 'Fundação do centro em Loulé' },
        { value: '6+', label: 'Especialidades coordenadas' },
      ],
      cta: 'Conhecer toda a equipa',
    },
    testimonials_v2: {
      read_more: 'Ler mais avaliações no Google',
      featured_q: 'Durante anos sofri de dores crónicas de costas. A abordagem que a Rita fez ao problema foi sem dúvida transformadora — é como ter um corpo novo. A diferença que isto fez na minha qualidade de vida é difícil de descrever',
      featured_what: 'Fisioterapia · 18 meses de acompanhamento',
      t1_q: 'A minha fisioterapeuta é uma peça fundamental na minha vida. Procuro-a todas as semanas para cuidar da musculatura e aliviar dores',
      t1_what: 'Fisioterapia',
      t2_q: 'Aulas de Pilates com a Rita são excelentes — a componente humana aliada às terapias é fundamental. Compreende mesmo as necessidades de cada um',
      t2_what: 'Pilates Clínico',
    },
    homecta_v2: {
      opt1_title: 'WhatsApp agora',
      opt1_desc: 'A forma mais rápida de marcar. A maioria das mensagens é respondida em menos de 5 minutos no horário da clínica.',
      opt1_cta: 'Enviar mensagem',
      opt2_title: 'Falar ao telefone',
      opt2_desc: 'Preferes a voz humana? Estamos disponíveis durante o horário da clínica para tirar dúvidas e marcar contigo.',
      opt2_cta: '961 899 364',
      opt3_title: 'Vem conhecer',
      opt3_desc: 'No coração de Loulé, a 2 minutos do centro histórico. Estacionamento fácil na zona envolvente.',
      opt3_cta: 'Como chegar',
      info_hours: 'Seg–Sex 9h–19h · Sábados sob marcação',
    },
    stats: [
      { value: '20', label: 'Anos de experiência', suffix: '+' },
      { value: '500', label: 'Pacientes acompanhados', suffix: '+' },
      { value: '25', label: 'Terapias disponíveis', suffix: '' },
      { value: '100', label: 'Dedicação à tua saúde', suffix: '%' },
    ],
    services_card: {
      eyebrow: 'Os nossos serviços',
      heading: 'Dores, tensão, stress? Temos a resposta — e a pessoa certa para ti',
      body: 'Fisioterapia, massagens, holísticas, psicologia, estética — tudo disponível na mesma clínica, em Loulé. Sem listas de espera longas, sem deslocações desnecessárias.',
      cta: 'Ver todos os serviços',
    },
    whyus: {
      eyebrow: 'Porquê a Clínica Rita Guerreiro',
      heading: 'Porque a tua saúde merece mais do que uma consulta rápida',
      points: [
        { t: 'Tratamento feito para ti, não para a média', d: 'O teu corpo, a tua história, o teu ritmo. Cada plano de tratamento começa por ouvir — e só depois agir.' },
        { t: 'Tudo no mesmo sítio, sem deslocações', d: 'Fisioterapia, psicologia, estética, nutrição — num só espaço em Loulé. Mais tempo para ti, menos stress logístico.' },
        { t: 'Profissionais que te acompanham de verdade', d: 'Não mudas de terapeuta a cada consulta. A tua equipa conhece-te, acompanha-te e preocupa-se com os teus resultados.' },
        { t: 'Sem listas de espera intermináveis', d: 'Marcação rápida por WhatsApp ou telefone. A maioria dos utentes consegue consulta na mesma semana.' },
      ],
    },
    services_overview: {
      eyebrow: 'Serviços',
      heading: 'Seja qual for o motivo que te traz, temos alguém para ti',
    },
    testimonials: {
      eyebrow: 'Testemunhos reais',
      heading: 'O que dizem os que já sentiram a diferença',
    },
    homecta: {
      eyebrow: 'Dá o primeiro passo hoje',
      heading: 'A tua recuperação começa com uma mensagem',
      body: 'Fala connosco agora — a maioria das marcações fica resolvida em menos de 5 minutos.',
      addr: 'Rua Padre António Vieira 58, Loulé · Seg–Sex 9h–19h · Sáb sob marcação',
      wa: 'WhatsApp agora',
      como_chegar: 'Como chegar',
    },
    agendar: 'Agendar',
    agendar_now: 'Agendar agora',
    ligar: 'Ligar',
    footer: {
      tagline: 'Centro de Terapias & Bem-Estar em Loulé. Cuidamos de ti, corpo e mente.',
      horario: 'Seg–Sex · 9h–19h · Sáb sob marcação',
      direitos: 'Todos os direitos reservados',
      col1: 'Fisioterapia & Saúde',
      col2: 'Massagens & Holísticas',
      col3: 'Horário & Contacto',
      privacidade: 'Privacidade',
      termos: 'Termos',
      reclamacoes: 'Livro de Reclamações',
      horario_item: 'Seg-Sex · 9:00-19:00',
      sabado_item: 'Sábados · sob marcação',
      seg_sex_label: 'Seg–Sex',
      seg_sex_val: '9:00 – 19:00',
      sabado_label: 'Sábados',
      sabado_val: 'Sob marcação',
      telefone_label: 'Telefone',
      email_label: 'Email',
      morada: 'Rua Padre António Vieira 58, Loulé',
      links: {
        fisioterapia: 'Fisioterapia',
        nutricao: 'Nutrição',
        psicologia: 'Psicologia',
        bowen: 'Terapia de Bowen',
        massagens: 'Massagens',
        holisticas: 'Holísticas',
        depilacao: 'Depilação a Laser',
        pilates: 'Pilates Clínico',
      },
    },
    servicos_cat: {
      reabilitacao: 'Reabilitação',
      bemestar: 'Bem-Estar',
      movimento: 'Movimento',
      estetica: 'Estética',
    },
    contactos_title: 'Fale Connosco',
    contactos: {
      eyebrow: 'Contactos',
      heading: 'Vem ter connosco',
      sub: 'No coração de Loulé — Algarve.',
      morada_label: 'Morada',
      telefone_label: 'Telefone',
      horario_label: 'Horário',
      morada_val: 'Rua Padre António Vieira 58\n8100-611 Loulé',
      horario_val: 'Seg–Sex 9h–19h\nSábados sob marcação',
      maps_link: 'Abrir no Google Maps',
    },
    form: {
      nome: 'Nome', email: 'E-mail', telefone: 'Telefone',
      servico: 'Serviço', mensagem: 'Mensagem',
      seleciona: 'Seleciona', enviar: 'Enviar mensagem', enviado: 'Mensagem enviada!',
    },
    sobre: {
      eyebrow: 'Sobre',
      heading: 'A equipa que cuida de ti como se fosses da família',
      sub: 'Na Clínica Rita Guerreiro dedicamo-nos a melhorar a tua saúde, bem-estar e qualidade de vida — com atenção, continuidade e respeito por quem és.',
      mission_eyebrow: 'A nossa missão',
      mission_heading: 'Ajudar cada pessoa a viver melhor, sem limitações',
      mission_body: 'Em Loulé, reunimos uma equipa multidisciplinar pronta a receber qualquer pessoa — com ou sem histórico clínico, com mais ou menos urgência. Aqui não há casos simples nem complicados: há pessoas. E cada uma merece um plano pensado para ela.',
      mission_cta: 'Ver serviços',
      pillars: [
        { t: 'Personalizado', d: 'Não há dois casos iguais. Cada plano começa por te ouvir.' },
        { t: 'Clínica completa', d: 'Vários serviços de saúde e bem-estar no mesmo espaço.' },
        { t: 'Uma equipa que se preocupa', d: 'Profissionais experientes com foco em ti.' },
        { t: 'Respeito pela tua história', d: 'A tua vida e o teu corpo são sempre respeitados.' },
      ],
      story_eyebrow: 'História',
      story_heading: 'Um projeto nascido do amor por cuidar das pessoas',
      story_p1: 'A Clínica Rita Guerreiro nasceu da visão de criar um espaço diferente — onde a qualidade do cuidado é tão importante quanto a qualidade do tratamento.',
      story_p2: 'Desde 2022 recebemos pessoas de todas as idades, com histórias muito diferentes. O que fica igual em todas elas é a forma como as recebemos: com escuta, com atenção e com continuidade.',
      team_eyebrow: 'A nossa equipa',
      team_heading: 'Especialistas que se preocupam com quem têm à frente',
      team_body: 'A nossa equipa é composta por profissionais qualificados em diversas áreas da saúde, que trabalham juntos para te oferecer o melhor acompanhamento possível — coordenado, humano e eficaz.',
      team_specialties: [
        { role: 'Fisioterapia & Reabilitação', bio: 'Avaliação e tratamento de dor, lesão e disfunção músculo-esquelética com abordagem individual.' },
        { role: 'Osteopatia & ATM', bio: 'Tratamento manual estrutural e visceral para aliviar a causa da dor, não apenas os sintomas.' },
        { role: 'Acupuntura & Terapia Bowen', bio: 'Técnicas complementares para reequilíbrio do sistema nervoso e gestão da dor crónica.' },
        { role: 'Psicologia & Nutrição', bio: 'Apoio à saúde mental e alimentar — para uma abordagem verdadeiramente integrada do bem-estar.' },
      ],
      team_join_heading: 'Tens paixão pela saúde e pelo cuidado das pessoas?',
      team_join_body: 'Adorávamos conhecer-te. Estamos sempre abertos a receber profissionais apaixonados pelo bem-estar.',
      team_join_cta: 'Entrar em contacto →',
      espaco_eyebrow: 'O nosso espaço',
      espaco_heading: 'Um lugar pensado para te receber',
      espaco_body: 'Da receção às salas de tratamento, cada canto da clínica foi desenhado para te trazer calma — luz natural, materiais quentes e detalhes que tornam cada visita um momento só teu.',
      espaco_photos: [
        { src: 'assets/clinica/recepcao.jpg', label: 'Receção' },
        { src: 'assets/clinica/sala-massagem.jpg', label: 'Sala de massagem' },
        { src: 'assets/clinica/estudio-pilates.jpg', label: 'Estúdio de Pilates' },
        { src: 'assets/clinica/sala-relaxamento.jpg', label: 'Sala de relaxamento' },
        { src: 'assets/clinica/sala-holistica.jpg', label: 'Sala holística' },
        { src: 'assets/clinica/sala-clinica.jpg', label: 'Sala clínica' },
      ],
    },
    category: {
      inicio: 'Início',
      cta_heading: 'Pronto para marcar?',
      cta_body: 'Contacta-nos por WhatsApp, telefone ou presencialmente.',
      cta_btn: 'Agendar agora',
    },
    service: {
      inicio: 'Início',
      info_eyebrow: 'Informações',
      preco_label: 'Preço',
      marcacoes_label: 'Marcações',
      marcacoes_body: 'Por WhatsApp, telefone ou presencialmente na clínica.',
      agendar_btn: 'Agendar agora',
      ligar_btn: 'Ligar 961 899 364',
      sobre_heading: 'Sobre este tratamento',
      areas_label: 'Áreas de atuação',
      processo_eyebrow: 'O processo',
      processo_heading: 'Como funciona',
      steps: [
        { t: 'Primeira consulta', d: 'Falamos sobre o teu caso e historial de saúde.' },
        { t: 'Avaliação', d: 'Diagnóstico preciso e identificação das causas.' },
        { t: 'Plano personalizado', d: 'Criamos um plano adaptado aos teus objetivos.' },
        { t: 'Tratamento', d: 'Sessões focadas com acompanhamento contínuo.' },
        { t: 'Acompanhamento', d: 'Seguimos a tua evolução ao longo do tempo.' },
      ],
      outros_eyebrow_prefix: 'Outros serviços em',
      outros_heading: 'Continua a explorar',
      ver_todos_prefix: '→ Ver todos os serviços de',
    },
    sobre_title: 'Sobre a Clínica',
    meta: { tagline: 'Terapias & Bem-Estar' },
  },
  EN: {
    nav: {
      inicio: 'Home', servicos: 'Services', sobre: 'About', contactos: 'Contacts',
      mega_descs: {
        fisioterapia: 'Rehabilitation and movement',
        saude: 'Integral wellbeing',
        massagens: 'Relaxation and therapy',
        holisticas: 'Balance and energy',
        estetica: 'Beauty and care',
      },
    },
    nav_mobile: { inicio: 'Home', servicos: 'Services', sobre: 'About', contactos: 'Contacts' },
    hero: {
      badge: 'Loulé · Algarve · Since 2022',
      badge_v2: 'In Loulé since 2022',
      h1: ['Recover', 'Balance', 'Feel good'],
      desc: 'Physiotherapy, Osteopathy, Clinical Pilates, Psychology and more — at a clinic in Loulé where every person is treated with genuine attention and care.',
      cta: 'Book appointment',
      cta_secondary: 'Explore treatments',
      cta_tel: 'Call now',
      horario: 'Mon–Fri 9am–7pm · Saturdays by appointment',
      social_proof: '+500 patients treated · Google 5★',
      social_proof_v2: '+500 patients treated',
      next_slot_label: 'Next available',
      next_slot_value: 'Thursday · 2:30pm',
      next_slot_meta: 'Physiotherapy · 50 min',
      card_name: 'Rita Guerreiro Therapy Centre',
      card_addr: 'Rua Padre António Vieira 58, Loulé',
    },
    trust: {
      anos: 'years of practice',
      anos_desc: 'Established experience in physiotherapy and rehabilitation in the Algarve.',
      pacientes: 'Patients treated',
      terapias: 'Therapies available',
      cred_title: 'Professional licence',
      cred_desc: 'Physiotherapist registered with the Portuguese Order of Physiotherapists.',
    },
    services_menu: {
      '01_name': 'Physiotherapy',
      '02_name': 'Clinical Pilates',
      '03_name': 'Therapeutic Massage',
      '04_name': 'Psychology & Nutrition',
      '01_blurb': 'Individual assessment and treatment of pain, injury and dysfunction — for children and adults. Sessions of 50 to 80 minutes.',
      '02_blurb': 'Mindful movement supervised by a physiotherapist — adapted to back pain, pregnancy, post-surgery and injury prevention.',
      '03_blurb': 'Therapeutic massages, deep tissue, pre/post-natal, craniosacral and the exclusive RG Signature Massage (80 min).',
      '04_blurb': 'Psychological support and tailored nutrition — because health is more than the body.',
    },
    meet: {
      eyebrow: 'Meet Rita',
      heading: 'The person behind the practice',
      p1: 'Rita Guerreiro founded this clinic in Loulé with a simple belief: every person deserves to be heard before being treated. Over two decades in physiotherapy taught her that the best results come from individual plans — not generic protocols.',
      p2: 'Today she leads a multidisciplinary team working together so you no longer need to change clinic for each need. Everything in one place, with continuity and respect for your story.',
      card_label: 'Founder · Physiotherapist',
      card_name: 'Rita Guerreiro',
      card_credentials: 'Physiotherapist · Specialised in TMJ, Vestibular and Clinical Pilates',
      facts: [
        { value: '2015', label: 'Start of clinical practice' },
        { value: '2022', label: 'Clinic founded in Loulé' },
        { value: '6+', label: 'Coordinated specialties' },
      ],
      cta: 'Meet the full team',
    },
    testimonials_v2: {
      read_more: 'Read more reviews on Google',
      featured_q: 'For years I suffered from chronic back pain. The way Rita approached the problem was truly transformative — it feels like having a new body. The difference it has made to my quality of life is hard to describe',
      featured_what: 'Physiotherapy · 18 months of treatment',
      t1_q: 'My physiotherapist is a key part of my life. I see her every week to care for my muscles and ease pain',
      t1_what: 'Physiotherapy',
      t2_q: 'Pilates classes with Rita are excellent — the human side combined with the therapies makes all the difference. She truly understands each person’s needs',
      t2_what: 'Clinical Pilates',
    },
    homecta_v2: {
      opt1_title: 'WhatsApp now',
      opt1_desc: 'The fastest way to book. Most messages are answered in under 5 minutes during clinic hours.',
      opt1_cta: 'Send message',
      opt2_title: 'Call us',
      opt2_desc: 'Prefer a human voice? Available during clinic hours to answer questions and book with you.',
      opt2_cta: '961 899 364',
      opt3_title: 'Come visit',
      opt3_desc: 'In the heart of Loulé, 2 minutes from the historic centre. Easy parking nearby.',
      opt3_cta: 'Get directions',
      info_hours: 'Mon–Fri 9am–7pm · Saturdays by appointment',
    },
    stats: [
      { value: '20', label: 'Years of experience', suffix: '+' },
      { value: '500', label: 'Patients treated', suffix: '+' },
      { value: '25', label: 'Therapies available', suffix: '' },
      { value: '100', label: 'Commitment to your health', suffix: '%' },
    ],
    services_card: {
      eyebrow: 'Our services',
      heading: 'Pain, tension, stress? We have the answer — and the right person for you',
      body: 'Physiotherapy, massage, holistic therapies, psychology, aesthetics — all available at one clinic in Loulé. No long waiting lists, no unnecessary trips.',
      cta: 'View all services',
    },
    whyus: {
      eyebrow: 'Why Rita Guerreiro Clinic',
      heading: 'Because your health deserves more than a quick appointment',
      points: [
        { t: 'Treatment made for you, not the average', d: 'Your body, your story, your pace. Every treatment plan starts by listening — then acting.' },
        { t: 'Everything in one place', d: 'Physiotherapy, psychology, aesthetics, nutrition — in one space in Loulé. More time for you, less logistical stress.' },
        { t: 'Professionals who truly accompany you', d: "You don't change therapist every appointment. Your team knows you, follows your progress, and cares about your results." },
        { t: 'No endless waiting lists', d: 'Quick booking via WhatsApp or phone. Most patients get an appointment within the same week.' },
      ],
    },
    services_overview: {
      eyebrow: 'Services',
      heading: 'Whatever brings you here, we have someone for you',
    },
    testimonials: {
      eyebrow: 'Real testimonials',
      heading: 'What those who felt the difference have to say',
    },
    homecta: {
      eyebrow: 'Take the first step today',
      heading: 'Your recovery starts with a message',
      body: 'Talk to us now — most bookings are sorted in under 5 minutes.',
      addr: 'Rua Padre António Vieira 58, Loulé · Mon–Fri 9am–7pm · Sat by appointment',
      wa: 'WhatsApp now',
      como_chegar: 'Get directions',
    },
    agendar: 'Book',
    agendar_now: 'Book now',
    ligar: 'Call',
    footer: {
      tagline: 'Therapy & Wellness Centre in Loulé. We care for you, body and mind.',
      horario: 'Mon–Fri · 9am–7pm · Sat by appointment',
      direitos: 'All rights reserved',
      col1: 'Physiotherapy & Health',
      col2: 'Massages & Holistic',
      col3: 'Hours & Contact',
      privacidade: 'Privacy',
      termos: 'Terms',
      reclamacoes: 'Complaints Book',
      horario_item: 'Mon–Fri · 9:00–19:00',
      sabado_item: 'Saturdays · by appointment',
    },
    servicos_cat: {
      reabilitacao: 'Rehabilitation',
      bemestar: 'Wellness',
      movimento: 'Movement',
      estetica: 'Aesthetics',
    },
    contactos_title: 'Contact Us',
    contactos: {
      eyebrow: 'Contacts',
      heading: 'Come find us',
      sub: 'In the heart of Loulé — Algarve.',
      morada_label: 'Address',
      telefone_label: 'Phone',
      horario_label: 'Hours',
      morada_val: 'Rua Padre António Vieira 58\n8100-611 Loulé',
      horario_val: 'Mon–Fri 9am–7pm\nSaturdays by appointment',
      maps_link: 'Open in Google Maps',
    },
    form: {
      nome: 'Name', email: 'E-mail', telefone: 'Phone',
      servico: 'Service', mensagem: 'Message',
      seleciona: 'Select', enviar: 'Send message', enviado: 'Message sent!',
    },
    sobre: {
      eyebrow: 'About',
      heading: 'The team that cares for you like family',
      sub: 'At Rita Guerreiro Clinic we are dedicated to improving your health, well-being and quality of life — with attention, continuity and respect for who you are.',
      mission_eyebrow: 'Our mission',
      mission_heading: 'Helping each person live better, without limitations',
      mission_body: 'In Loulé, we bring together a multidisciplinary team ready to welcome anyone — with or without a clinical history, with more or less urgency. There are no simple or complicated cases here: there are people. And each one deserves a plan made for them.',
      mission_cta: 'View services',
      pillars: [
        { t: 'Personalised', d: 'No two cases are the same. Every plan starts by listening to you.' },
        { t: 'Full clinic', d: 'Multiple health and wellness services in one space.' },
        { t: 'A team that cares', d: 'Experienced professionals focused on you.' },
        { t: 'Respect for your story', d: 'Your life and your body are always respected.' },
      ],
      story_eyebrow: 'Story',
      story_heading: 'A project born from a love of caring for people',
      story_p1: 'Rita Guerreiro Clinic was born from the vision of creating a different space — where the quality of care is as important as the quality of treatment.',
      story_p2: 'Since 2022 we have welcomed people of all ages, with very different stories. What stays the same for all of them is the way we receive them: with listening, with attention and with continuity.',
      team_eyebrow: 'Our team',
      team_heading: 'Specialists who care about the person in front of them',
      team_body: 'Our team is made up of qualified professionals in various health fields, working together to offer you the best possible support — coordinated, human and effective.',
      team_specialties: [
        { role: 'Physiotherapy & Rehabilitation', bio: 'Assessment and treatment of pain, injury and musculoskeletal dysfunction with an individual approach.' },
        { role: 'Osteopathy & TMJ', bio: 'Structural and visceral manual treatment to relieve the cause of pain, not just the symptoms.' },
        { role: 'Acupuncture & Bowen Therapy', bio: 'Complementary techniques for rebalancing the nervous system and managing chronic pain.' },
        { role: 'Psychology & Nutrition', bio: 'Mental and nutritional health support — for a truly integrated approach to well-being.' },
      ],
      team_join_heading: 'Passionate about health and caring for people?',
      team_join_body: "We'd love to meet you. We're always open to welcoming professionals passionate about well-being.",
      team_join_cta: 'Get in touch →',
      espaco_eyebrow: 'Our space',
      espaco_heading: 'A place designed to welcome you',
      espaco_body: 'From the reception to the treatment rooms, every corner of the clinic was designed to bring you calm — natural light, warm materials and details that make each visit a moment that is yours alone.',
      espaco_photos: [
        { src: 'assets/clinica/recepcao.jpg', label: 'Reception' },
        { src: 'assets/clinica/sala-massagem.jpg', label: 'Massage room' },
        { src: 'assets/clinica/estudio-pilates.jpg', label: 'Pilates studio' },
        { src: 'assets/clinica/sala-relaxamento.jpg', label: 'Relaxation room' },
        { src: 'assets/clinica/sala-holistica.jpg', label: 'Holistic room' },
        { src: 'assets/clinica/sala-clinica.jpg', label: 'Clinical room' },
      ],
    },
    category: {
      inicio: 'Home',
      cta_heading: 'Ready to book?',
      cta_body: 'Contact us via WhatsApp, phone or in person.',
      cta_btn: 'Book now',
    },
    service: {
      inicio: 'Home',
      info_eyebrow: 'Information',
      preco_label: 'Price',
      marcacoes_label: 'Bookings',
      marcacoes_body: 'Via WhatsApp, phone or in person at the clinic.',
      agendar_btn: 'Book now',
      ligar_btn: 'Call 961 899 364',
      sobre_heading: 'About this treatment',
      areas_label: 'Areas of focus',
      processo_eyebrow: 'The process',
      processo_heading: 'How it works',
      steps: [
        { t: 'First appointment', d: 'We talk about your case and health history.' },
        { t: 'Assessment', d: 'Precise diagnosis and identification of causes.' },
        { t: 'Personalised plan', d: 'We create a plan adapted to your goals.' },
        { t: 'Treatment', d: 'Focused sessions with continuous monitoring.' },
        { t: 'Follow-up', d: 'We follow your progress over time.' },
      ],
      outros_eyebrow_prefix: 'Other services in',
      outros_heading: 'Keep exploring',
      ver_todos_prefix: '→ View all services in',
    },
    sobre_title: 'About the Clinic',
    meta: { tagline: 'Therapies & Wellness' },
  },
  ES: {
    nav: {
      inicio: 'Inicio', servicos: 'Servicios', sobre: 'Sobre nosotros', contactos: 'Contacto',
      mega_descs: {
        fisioterapia: 'Rehabilitación y movimiento',
        saude: 'Bienestar integral',
        massagens: 'Relajación y terapia',
        holisticas: 'Equilibrio y energía',
        estetica: 'Belleza y cuidado',
      },
    },
    nav_mobile: { inicio: 'Inicio', servicos: 'Servicios', sobre: 'Sobre nosotros', contactos: 'Contacto' },
    hero: {
      badge: 'Loulé · Algarve · Desde 2022',
      badge_v2: 'En Loulé desde 2022',
      h1: ['Recupérate', 'Equilíbrate', 'Siéntete bien'],
      desc: 'Fisioterapia, Osteopatía, Pilates Clínico, Psicología y mucho más — en una clínica en Loulé donde cada persona es tratada con atención y cuidado real.',
      cta: 'Reservar cita',
      cta_secondary: 'Ver tratamientos',
      cta_tel: 'Llamar ahora',
      horario: 'Lun–Vie 9h–19h · Sáb con cita previa',
      social_proof: '+500 pacientes acompañados · Google 5★',
      social_proof_v2: '+500 pacientes acompañados',
      next_slot_label: 'Próxima cita',
      next_slot_value: 'Jueves · 14h30',
      next_slot_meta: 'Fisioterapia · 50 min',
      card_name: 'Centro de Terapias Rita Guerreiro',
      card_addr: 'Rua Padre António Vieira 58, Loulé',
    },
    trust: {
      anos: 'años de práctica',
      anos_desc: 'Experiencia consolidada en fisioterapia y rehabilitación en el Algarve.',
      pacientes: 'Pacientes acompañados',
      terapias: 'Terapias disponibles',
      cred_title: 'Cédula profesional',
      cred_desc: 'Fisioterapeuta inscrita en el Colegio de Fisioterapeutas de Portugal.',
    },
    services_menu: {
      '01_name': 'Fisioterapia',
      '02_name': 'Pilates Clínico',
      '03_name': 'Masajes Terapéuticos',
      '04_name': 'Psicología & Nutrición',
      '01_blurb': 'Evaluación y tratamiento individual del dolor, lesión y disfunción — para niños y adultos. Sesiones de 50 a 80 minutos.',
      '02_blurb': 'Movimiento consciente supervisado por fisioterapeuta — adaptado a dolor lumbar, embarazo, posoperatorio y prevención de lesiones.',
      '03_blurb': 'Masajes terapéuticos, deep tissue, pre/posnatal, sacro-craneal y el exclusivo Masaje Firma RG (80 min).',
      '04_blurb': 'Acompañamiento psicológico y plan nutricional individualizado — porque la salud va más allá del cuerpo.',
    },
    meet: {
      eyebrow: 'Conoce a Rita',
      heading: 'La persona detrás del proyecto',
      p1: 'Rita Guerreiro fundó este centro en Loulé con una convicción sencilla: cada persona merece ser escuchada antes de ser tratada. Más de dos décadas en fisioterapia le enseñaron que los mejores resultados vienen de planes individuales — no de protocolos genéricos.',
      p2: 'Hoy lidera un equipo multidisciplinar que trabaja en conjunto para que no tengas que cambiar de clínica según la necesidad. Todo en un solo sitio, con continuidad y respeto por tu historia.',
      card_label: 'Fundadora · Fisioterapeuta',
      card_name: 'Rita Guerreiro',
      card_credentials: 'Fisioterapeuta · Especializada en ATM, Vestibular y Pilates Clínico',
      facts: [
        { value: '2015', label: 'Inicio de la práctica clínica' },
        { value: '2022', label: 'Fundación del centro en Loulé' },
        { value: '6+', label: 'Especialidades coordinadas' },
      ],
      cta: 'Conocer a todo el equipo',
    },
    testimonials_v2: {
      read_more: 'Leer más reseñas en Google',
      featured_q: 'Durante años sufrí dolores crónicos de espalda. El enfoque que Rita le dio al problema fue sin duda transformador — es como tener un cuerpo nuevo. La diferencia que esto ha supuesto en mi calidad de vida es difícil de describir',
      featured_what: 'Fisioterapia · 18 meses de seguimiento',
      t1_q: 'Mi fisioterapeuta es una pieza fundamental en mi vida. La busco todas las semanas para cuidar la musculatura y aliviar dolores',
      t1_what: 'Fisioterapia',
      t2_q: 'Las clases de Pilates con Rita son excelentes — el componente humano unido a las terapias es fundamental. Entiende realmente las necesidades de cada uno',
      t2_what: 'Pilates Clínico',
    },
    homecta_v2: {
      opt1_title: 'WhatsApp ahora',
      opt1_desc: 'La forma más rápida de reservar. La mayoría de los mensajes se responden en menos de 5 minutos en horario de clínica.',
      opt1_cta: 'Enviar mensaje',
      opt2_title: 'Llamar por teléfono',
      opt2_desc: '¿Prefieres la voz humana? Estamos disponibles durante el horario de clínica para resolver dudas y reservar contigo.',
      opt2_cta: '961 899 364',
      opt3_title: 'Ven a conocernos',
      opt3_desc: 'En el corazón de Loulé, a 2 minutos del centro histórico. Aparcamiento fácil en la zona.',
      opt3_cta: 'Cómo llegar',
      info_hours: 'Lun–Vie 9h–19h · Sábados con cita previa',
    },
    stats: [
      { value: '20', label: 'Años de experiencia', suffix: '+' },
      { value: '500', label: 'Pacientes acompañados', suffix: '+' },
      { value: '25', label: 'Terapias disponibles', suffix: '' },
      { value: '100', label: 'Dedicación a tu salud', suffix: '%' },
    ],
    services_card: {
      eyebrow: 'Nuestros servicios',
      heading: '¿Dolores, tensión, estrés? Tenemos la respuesta — y la persona adecuada para ti',
      body: 'Fisioterapia, masajes, holísticas, psicología, estética — todo disponible en la misma clínica, en Loulé. Sin largas listas de espera, sin desplazamientos innecesarios.',
      cta: 'Ver todos los servicios',
    },
    whyus: {
      eyebrow: 'Por qué la Clínica Rita Guerreiro',
      heading: 'Porque tu salud merece más que una consulta rápida',
      points: [
        { t: 'Tratamiento hecho para ti, no para la media', d: 'Tu cuerpo, tu historia, tu ritmo. Cada plan de tratamiento empieza por escucharte — y solo después actuar.' },
        { t: 'Todo en el mismo sitio, sin desplazamientos', d: 'Fisioterapia, psicología, estética, nutrición — en un solo espacio en Loulé. Más tiempo para ti, menos estrés logístico.' },
        { t: 'Profesionales que te acompañan de verdad', d: 'No cambias de terapeuta en cada consulta. Tu equipo te conoce, te acompaña y se preocupa por tus resultados.' },
        { t: 'Sin listas de espera interminables', d: 'Reserva rápida por WhatsApp o teléfono. La mayoría de los pacientes consigue cita en la misma semana.' },
      ],
    },
    services_overview: {
      eyebrow: 'Servicios',
      heading: 'Sea cual sea el motivo que te trae, tenemos a alguien para ti',
    },
    testimonials: {
      eyebrow: 'Testimonios reales',
      heading: 'Lo que dicen quienes ya han sentido la diferencia',
    },
    homecta: {
      eyebrow: 'Da el primer paso hoy',
      heading: 'Tu recuperación empieza con un mensaje',
      body: 'Habla con nosotros ahora — la mayoría de las reservas se resuelven en menos de 5 minutos.',
      addr: 'Rua Padre António Vieira 58, Loulé · Lun–Vie 9h–19h · Sáb con cita previa',
      wa: 'WhatsApp ahora',
      como_chegar: 'Cómo llegar',
    },
    agendar: 'Reservar',
    agendar_now: 'Reservar ahora',
    ligar: 'Llamar',
    footer: {
      tagline: 'Centro de Terapias & Bienestar en Loulé. Cuidamos de ti, cuerpo y mente.',
      horario: 'Lun–Vie · 9h–19h · Sáb con cita previa',
      direitos: 'Todos los derechos reservados',
      col1: 'Fisioterapia & Salud',
      col2: 'Masajes & Holísticas',
      col3: 'Horario & Contacto',
      privacidade: 'Privacidad',
      termos: 'Términos',
      reclamacoes: 'Libro de Reclamaciones',
      horario_item: 'Lun–Vie · 9:00–19:00',
      sabado_item: 'Sábados · con cita previa',
      seg_sex_label: 'Lun–Vie',
      seg_sex_val: '9:00 – 19:00',
      sabado_label: 'Sábados',
      sabado_val: 'Con cita previa',
      telefone_label: 'Teléfono',
      email_label: 'Email',
      morada: 'Rua Padre António Vieira 58, Loulé',
      links: {
        fisioterapia: 'Fisioterapia',
        nutricao: 'Nutrición',
        psicologia: 'Psicología',
        bowen: 'Terapia Bowen',
        massagens: 'Masajes',
        holisticas: 'Holísticas',
        depilacao: 'Depilación Láser',
        pilates: 'Pilates Clínico',
      },
    },
    servicos_cat: {
      reabilitacao: 'Rehabilitación',
      bemestar: 'Bienestar',
      movimento: 'Movimiento',
      estetica: 'Estética',
    },
    contactos_title: 'Habla con Nosotros',
    contactos: {
      eyebrow: 'Contacto',
      heading: 'Ven a vernos',
      sub: 'En el corazón de Loulé — Algarve.',
      morada_label: 'Dirección',
      telefone_label: 'Teléfono',
      horario_label: 'Horario',
      morada_val: 'Rua Padre António Vieira 58\n8100-611 Loulé',
      horario_val: 'Lun–Vie 9h–19h\nSábados con cita previa',
      maps_link: 'Abrir en Google Maps',
    },
    form: {
      nome: 'Nombre', email: 'E-mail', telefone: 'Teléfono',
      servico: 'Servicio', mensagem: 'Mensaje',
      seleciona: 'Selecciona', enviar: 'Enviar mensaje', enviado: '¡Mensaje enviado!',
    },
    sobre: {
      eyebrow: 'Sobre nosotros',
      heading: 'El equipo que te cuida como si fueras de la familia',
      sub: 'En la Clínica Rita Guerreiro nos dedicamos a mejorar tu salud, bienestar y calidad de vida — con atención, continuidad y respeto por quien eres.',
      mission_eyebrow: 'Nuestra misión',
      mission_heading: 'Ayudar a cada persona a vivir mejor, sin limitaciones',
      mission_body: 'En Loulé reunimos un equipo multidisciplinar listo para recibir a cualquier persona — con o sin historial clínico, con más o menos urgencia. Aquí no hay casos simples ni complicados: hay personas. Y cada una merece un plan pensado para ella.',
      mission_cta: 'Ver servicios',
      pillars: [
        { t: 'Personalizado', d: 'No hay dos casos iguales. Cada plan empieza por escucharte.' },
        { t: 'Clínica completa', d: 'Varios servicios de salud y bienestar en el mismo espacio.' },
        { t: 'Un equipo que se preocupa', d: 'Profesionales experimentados centrados en ti.' },
        { t: 'Respeto por tu historia', d: 'Tu vida y tu cuerpo son siempre respetados.' },
      ],
      story_eyebrow: 'Historia',
      story_heading: 'Un proyecto nacido del amor por cuidar de las personas',
      story_p1: 'La Clínica Rita Guerreiro nació de la visión de crear un espacio diferente — donde la calidad del cuidado es tan importante como la calidad del tratamiento.',
      story_p2: 'Desde 2022 recibimos personas de todas las edades, con historias muy distintas. Lo que se mantiene igual en todas ellas es la forma en que las recibimos: con escucha, con atención y con continuidad.',
      team_eyebrow: 'Nuestro equipo',
      team_heading: 'Especialistas que se preocupan por quien tienen delante',
      team_body: 'Nuestro equipo está formado por profesionales cualificados en diversas áreas de la salud, que trabajan juntos para ofrecerte el mejor acompañamiento posible — coordinado, humano y eficaz.',
      team_specialties: [
        { role: 'Fisioterapia & Rehabilitación', bio: 'Evaluación y tratamiento de dolor, lesión y disfunción músculo-esquelética con enfoque individual.' },
        { role: 'Osteopatía & ATM', bio: 'Tratamiento manual estructural y visceral para aliviar la causa del dolor, no solo los síntomas.' },
        { role: 'Acupuntura & Terapia Bowen', bio: 'Técnicas complementarias para reequilibrio del sistema nervioso y gestión del dolor crónico.' },
        { role: 'Psicología & Nutrición', bio: 'Apoyo a la salud mental y alimentaria — para un enfoque verdaderamente integrado del bienestar.' },
      ],
      team_join_heading: '¿Tienes pasión por la salud y por cuidar de las personas?',
      team_join_body: 'Nos encantaría conocerte. Estamos siempre abiertos a recibir profesionales apasionados por el bienestar.',
      team_join_cta: 'Ponerse en contacto →',
      espaco_eyebrow: 'Nuestro espacio',
      espaco_heading: 'Un lugar pensado para recibirte',
      espaco_body: 'Desde la recepción a las salas de tratamiento, cada rincón de la clínica fue diseñado para traerte calma — luz natural, materiales cálidos y detalles que hacen de cada visita un momento solo tuyo.',
      espaco_photos: [
        { src: 'assets/clinica/recepcao.jpg', label: 'Recepción' },
        { src: 'assets/clinica/sala-massagem.jpg', label: 'Sala de masaje' },
        { src: 'assets/clinica/estudio-pilates.jpg', label: 'Estudio de Pilates' },
        { src: 'assets/clinica/sala-relaxamento.jpg', label: 'Sala de relajación' },
        { src: 'assets/clinica/sala-holistica.jpg', label: 'Sala holística' },
        { src: 'assets/clinica/sala-clinica.jpg', label: 'Sala clínica' },
      ],
    },
    category: {
      inicio: 'Inicio',
      cta_heading: '¿Listo para reservar?',
      cta_body: 'Contáctanos por WhatsApp, teléfono o presencialmente.',
      cta_btn: 'Reservar ahora',
    },
    service: {
      inicio: 'Inicio',
      info_eyebrow: 'Información',
      preco_label: 'Precio',
      marcacoes_label: 'Reservas',
      marcacoes_body: 'Por WhatsApp, teléfono o presencialmente en la clínica.',
      agendar_btn: 'Reservar ahora',
      ligar_btn: 'Llamar 961 899 364',
      sobre_heading: 'Sobre este tratamiento',
      areas_label: 'Áreas de actuación',
      processo_eyebrow: 'El proceso',
      processo_heading: 'Cómo funciona',
      steps: [
        { t: 'Primera consulta', d: 'Hablamos sobre tu caso e historial de salud.' },
        { t: 'Evaluación', d: 'Diagnóstico preciso e identificación de las causas.' },
        { t: 'Plan personalizado', d: 'Creamos un plan adaptado a tus objetivos.' },
        { t: 'Tratamiento', d: 'Sesiones enfocadas con seguimiento continuo.' },
        { t: 'Seguimiento', d: 'Seguimos tu evolución a lo largo del tiempo.' },
      ],
      outros_eyebrow_prefix: 'Otros servicios en',
      outros_heading: 'Sigue explorando',
      ver_todos_prefix: '→ Ver todos los servicios de',
    },
    sobre_title: 'Sobre la Clínica',
    meta: { tagline: 'Terapias & Bienestar' },
  },
};

const LangContext = React.createContext({ lang: 'PT', changeLang: () => {} });

function useLang() {
  const ctx = React.useContext(LangContext);
  const lang = typeof ctx === 'string' ? ctx : ctx.lang;
  const t = (path) => {
    const keys = path.split('.');
    let v = TRANSLATIONS[lang] || TRANSLATIONS.PT;
    for (const k of keys) v = v?.[k];
    return v ?? path;
  };
  return { lang, t };
}

function LangProvider({ children }) {
  const saved = (typeof localStorage !== 'undefined' && localStorage.getItem('rg_lang')) || 'PT';
  const [lang, setLang] = React.useState(['PT','EN','FR','ES'].includes(saved) ? saved : 'PT');
  const changeLang = (code) => {
    setLang(code);
    if (typeof document !== 'undefined') {
      const map = { PT: 'pt-PT', EN: 'en', FR: 'fr', ES: 'es' };
      document.documentElement.lang = map[code] || 'pt-PT';
    }
    localStorage.setItem('rg_lang', code);
  };
  React.useEffect(() => {
    if (typeof document !== 'undefined') {
      const map = { PT: 'pt-PT', EN: 'en', FR: 'fr', ES: 'es' };
      document.documentElement.lang = map[lang] || 'pt-PT';
    }
  }, [lang]);
  return React.createElement(LangContext.Provider, { value: { lang, changeLang } }, children);
}

Object.assign(window, { TRANSLATIONS, LangContext, LangProvider, useLang });
